### ISSUE TITLE
Not working with DockerHub?

### ISSUE THREAD

**Issue by polarathene** [consideRatio/discourse-sso-oidc-bridge#3]
The README states:

> The Flask application can be deployed using a Docker image that is also within this repo and published to docker hub as consideratio/discourse-sso-oidc-bridge.

But there is no link to the dockerhub page. I tried to locate it via google, nothing under that image or user when queried. Searched your username on DockerHub and identified it [here](https://hub.docker.com/r/consideratio/discourse-sso-oidc-bridge).

Output from terminal trying to use it:

```
> docker-compose up
Pulling discourse_bridge (consideratio/discourse-sso-oidc-bridge:latest)...
ERROR: manifest for consideratio/discourse-sso-oidc-bridge:latest not found
```

Checking tags, there is no `latest` tag, so README should probably make a note of that as the command implies like most other docker images that `latest` is supported. Oddly despite the [DockerHub tags page](https://hub.docker.com/r/consideratio/discourse-sso-oidc-bridge/tags) sorting being set to "latest", the first result for me is `0.1.7`(9 months ago), you'd have to scroll down through the tags to realize that's not the case, or check to see what the latest version is via the [CHANGELOG](https://github.com/consideRatio/discourse-sso-oidc-bridge/blob/master/ChangeLog), so `0.1.9` is the latest.

## Solution

Support a `latest` tag, or update the README to use the latest tag.

**Comment by consideRatio** [comment]
There is now a latest tag along with some badges to indicate available versions and build status etc! Thanks for reporting your experience with this @polarathene! :heart: :sunflower:
